import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/component/Global/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/component/Global/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mobil Secound",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Toaster
          toastOptions={{
            style: {
              background: "rgb(19 78 74)",
              color: "rgb(250 250 250)",
              fontWeight: 200,
              border: "1px solid rgb(13 148 136 / 0.4)",
            },
          }}
          position="bottom-right"
        />
        <Footer />
        </body>
    </html>
  );
}
